# Generated by Django 5.2.11 on 2026-03-02 15:07

import apps.applications.models
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('resume', models.FileField(upload_to=apps.applications.models._application_resume_upload_to, validators=[apps.core.validators.validate_resume_file])),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['applicant', 'applied_at'], name='application_applica_bd212a_idx'), models.Index(fields=['job', 'applied_at'], name='application_job_id_ae1b06_idx'), models.Index(fields=['status', 'applied_at'], name='application_status_89c2ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'applicant'), name='uniq_application_job_applicant')],
            },
        ),
    ]
